In [5]:
!pip install numpy==2.0.2
!pip install pandas==2.2.2
!pip install tensorflow_cpu==2.18.0

Requirement already satisfied: numpy==2.0.2 in /opt/conda/lib/python3.12/site-packages (2.0.2)
Requirement already satisfied: pandas==2.2.2 in /opt/conda/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Requirement already satisfied: tensorflow_cpu==2.18.0 in /opt/conda/lib/python3.12/site-packages (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (3.4.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (2.32.3)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (75.8.0)
Requirement already satisfied: six>=1.12.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (1.74.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (3.11.1)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (3.14.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (0.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow_cpu==2.18.0) (0.45.1)
Requirement already satisfied: rich in /opt/conda/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow_cpu==2.18.0) (14.1.0)
Requirement already satisfied: namex in /opt/conda/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow_cpu==2.18.0) (0.1.0)
Requirement already satisfied: optree in /opt/conda/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow_cpu==2.18.0) (0.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (2024.12.14)
Requirement already satisfied: markdown>=2.6.8 in /opt/conda/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/conda/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /opt/conda/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow_cpu==2.18.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow_cpu==2.18.0) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow_cpu==2.18.0) (0.1.2)

In [4]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [3]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

In [6]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [7]:
concrete_data.shape

(1030, 9)

In [8]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [9]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [10]:
concrete_data_columns = concrete_data.columns

In [11]:
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [12]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [13]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [14]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [15]:
n_cols = predictors_norm.shape[1] # number of predictors

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

In [17]:
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [18]:
model = regression_model()

In [ ]:
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 2s - 75ms/step - loss: 1669.4596 - val_loss: 1147.8590
Epoch 2/100
23/23 - 0s - 8ms/step - loss: 1543.0404 - val_loss: 1023.0625
Epoch 3/100
23/23 - 0s - 16ms/step - loss: 1337.5677 - val_loss: 825.4695
Epoch 4/100
23/23 - 0s - 13ms/step - loss: 1019.3705 - val_loss: 569.9060
Epoch 5/100
23/23 - 0s - 8ms/step - loss: 647.0246 - val_loss: 326.6288
Epoch 6/100
23/23 - 0s - 7ms/step - loss: 362.0468 - val_loss: 196.7435
Epoch 7/100
23/23 - 0s - 7ms/step - loss: 250.7067 - val_loss: 167.5495
Epoch 8/100
23/23 - 0s - 7ms/step - loss: 220.8868 - val_loss: 166.3846
Epoch 9/100
23/23 - 0s - 8ms/step - loss: 206.5519 - val_loss: 168.6010
Epoch 10/100
23/23 - 0s - 7ms/step - loss: 194.7734 - val_loss: 172.2715
Epoch 11/100
23/23 - 0s - 7ms/step - loss: 186.6489 - val_loss: 170.6425
Epoch 12/100
23/23 - 0s - 8ms/step - loss: 180.0536 - val_loss: 167.3528
Epoch 13/100
23/23 - 0s - 7ms/step - loss: 175.6504 - val_loss: 168.0294
Epoch 14/100
23/23 - 0s - 7ms/step - loss: 171.3574 - val_loss: 167.8547
Epoch 15/100
23/23 - 0s - 7ms/step - loss: 167.5795 - val_loss: 166.6396
Epoch 16/100
23/23 - 0s - 7ms/step - loss: 164.6533 - val_loss: 166.6670
Epoch 17/100
23/23 - 0s - 9ms/step - loss: 162.2017 - val_loss: 167.1618
Epoch 18/100
23/23 - 0s - 7ms/step - loss: 160.2319 - val_loss: 163.4342
Epoch 19/100
23/23 - 0s - 8ms/step - loss: 157.5818 - val_loss: 164.4476
Epoch 20/100
23/23 - 0s - 8ms/step - loss: 155.7395 - val_loss: 163.4511
Epoch 21/100
23/23 - 0s - 8ms/step - loss: 153.5947 - val_loss: 161.5768
Epoch 22/100
23/23 - 0s - 8ms/step - loss: 152.4665 - val_loss: 161.1614
Epoch 23/100
23/23 - 0s - 8ms/step - loss: 150.0495 - val_loss: 159.4270
Epoch 24/100
23/23 - 0s - 8ms/step - loss: 148.7517 - val_loss: 156.7091
Epoch 25/100
23/23 - 0s - 8ms/step - loss: 146.7523 - val_loss: 159.4089
Epoch 26/100
23/23 - 0s - 8ms/step - loss: 145.2435 - val_loss: 159.2402
Epoch 27/100
23/23 - 0s - 8ms/step - loss: 144.3129 - val_loss: 155.8189
Epoch 28/100
23/23 - 0s - 8ms/step - loss: 142.0851 - val_loss: 157.7472
Epoch 29/100
23/23 - 0s - 7ms/step - loss: 140.9066 - val_loss: 158.3591
Epoch 30/100
23/23 - 0s - 8ms/step - loss: 139.0079 - val_loss: 155.3404
Epoch 31/100
23/23 - 0s - 7ms/step - loss: 137.9856 - val_loss: 155.5894
Epoch 32/100
23/23 - 0s - 8ms/step - loss: 135.9447 - val_loss: 157.6453
Epoch 33/100
23/23 - 0s - 8ms/step - loss: 134.9108 - val_loss: 154.0124
Epoch 34/100
23/23 - 0s - 8ms/step - loss: 133.0246 - val_loss: 153.5988
Epoch 35/100
23/23 - 0s - 7ms/step - loss: 131.2639 - val_loss: 154.4480
Epoch 36/100
23/23 - 0s - 7ms/step - loss: 129.6822 - val_loss: 152.9685
Epoch 37/100
23/23 - 0s - 7ms/step - loss: 128.0892 - val_loss: 155.3383
Epoch 38/100
23/23 - 0s - 8ms/step - loss: 126.3329 - val_loss: 153.4724
Epoch 39/100
23/23 - 0s - 7ms/step - loss: 124.4043 - val_loss: 153.8029
Epoch 40/100
23/23 - 0s - 8ms/step - loss: 122.4367 - val_loss: 150.2532
Epoch 41/100
23/23 - 0s - 7ms/step - loss: 119.6680 - val_loss: 149.0884
Epoch 42/100
23/23 - 0s - 8ms/step - loss: 117.4519 - val_loss: 148.3464
Epoch 43/100
23/23 - 0s - 8ms/step - loss: 114.7070 - val_loss: 146.1987
Epoch 44/100
23/23 - 0s - 8ms/step - loss: 112.7454 - val_loss: 148.5038
Epoch 45/100
23/23 - 0s - 8ms/step - loss: 109.6538 - val_loss: 144.1141
Epoch 46/100
23/23 - 0s - 7ms/step - loss: 106.8919 - val_loss: 145.9931
Epoch 47/100
23/23 - 0s - 7ms/step - loss: 104.1374 - val_loss: 140.1942
Epoch 48/100
23/23 - 0s - 7ms/step - loss: 100.7394 - val_loss: 139.4231
Epoch 49/100
23/23 - 0s - 8ms/step - loss: 98.0423 - val_loss: 135.5363
Epoch 50/100
23/23 - 0s - 9ms/step - loss: 94.8640 - val_loss: 134.2511
Epoch 51/100
23/23 - 0s - 8ms/step - loss: 91.7568 - val_loss: 129.9315
Epoch 52/100
23/23 - 0s - 8ms/step - loss: 88.9824 - val_loss: 132.5673
Epoch 53/100
23/23 - 0s - 9ms/step - loss: 85.8273 - val_loss: 130.7458
Epoch 54/100
23/23 - 0s - 8ms/step - loss: 82.9855 - val_loss: 127.4074
Epoch 55/100
23/23 - 0s - 9ms/step - loss: 79.5997 - val_loss: 124.0061
Epoch 56/100
23/23 - 0s - 8ms/step - loss: 77.1900 - val_loss: 121.3385
Epoch 57/100
23/23 - 0s - 7ms/step - loss: 74.4984 - val_loss: 120.1306
Epoch 58/100
23/23 - 0s - 8ms/step - loss: 72.1129 - val_loss: 122.9919
Epoch 59/100
23/23 - 0s - 9ms/step - loss: 70.4890 - val_loss: 116.0261
Epoch 60/100
23/23 - 0s - 8ms/step - loss: 67.1056 - val_loss: 117.2314
Epoch 61/100
23/23 - 0s - 8ms/step - loss: 64.7897 - val_loss: 114.7890
Epoch 62/100
23/23 - 0s - 8ms/step - loss: 63.0903 - val_loss: 112.8964
Epoch 63/100
23/23 - 0s - 8ms/step - loss: 60.9795 - val_loss: 111.8370
Epoch 64/100
23/23 - 0s - 7ms/step - loss: 59.1606 - val_loss: 111.1122
Epoch 65/100
23/23 - 0s - 8ms/step - loss: 57.1716 - val_loss: 115.0422
Epoch 66/100
23/23 - 0s - 8ms/step - loss: 56.1961 - val_loss: 109.7966
Epoch 67/100
23/23 - 0s - 8ms/step - loss: 54.1831 - val_loss: 111.6157
Epoch 68/100
23/23 - 0s - 7ms/step - loss: 52.8991 - val_loss: 109.9881
Epoch 69/100
23/23 - 0s - 7ms/step - loss: 52.7673 - val_loss: 104.6033
Epoch 70/100
23/23 - 0s - 7ms/step - loss: 50.1394 - val_loss: 115.2606
Epoch 71/100
23/23 - 0s - 7ms/step - loss: 50.5489 - val_loss: 105.5934
Epoch 72/100
23/23 - 0s - 7ms/step - loss: 48.7542 - val_loss: 111.7013
Epoch 73/100
23/23 - 0s - 8ms/step - loss: 47.4145 - val_loss: 109.2432
Epoch 74/100
23/23 - 0s - 7ms/step - loss: 46.7877 - val_loss: 109.0236
Epoch 75/100
23/23 - 0s - 7ms/step - loss: 45.9935 - val_loss: 110.3814
Epoch 76/100
23/23 - 0s - 7ms/step - loss: 45.3636 - val_loss: 106.1475
Epoch 77/100
23/23 - 0s - 8ms/step - loss: 44.3294 - val_loss: 110.7156
Epoch 78/100
23/23 - 0s - 8ms/step - loss: 43.5396 - val_loss: 109.2179
Epoch 79/100
23/23 - 0s - 7ms/step - loss: 42.8470 - val_loss: 114.2252
Epoch 80/100
23/23 - 0s - 7ms/step - loss: 42.1861 - val_loss: 113.2662
Epoch 81/100
23/23 - 0s - 8ms/step - loss: 42.1619 - val_loss: 119.1848
Epoch 82/100